FnR.VetFront/Controllers/PostVisitCareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FnR.Databases;
using FnR.Models;
using FnR.Repositories;
using Newtonsoft.Json;

namespace FnR.VetFront.Controllers
{
    [Authorize]
    public class PostVisitCareController : Controller
    {
        private readonly VetRepository _vetRepo;
        private readonly ConditionRepository _conditionRepo;
        private readonly UserRepository _userRepo;
        public PostVisitCareController()
        {
            _vetRepo = new VetRepository(new FnRDbContext());
            _conditionRepo = new ConditionRepository(new FnRDbContext());
            _userRepo = new UserRepository(new FnRDbContext());
        }
        //
        // GET: /PostVisitCare/

        public ActionResult Index()
        {
            var username = HttpContext.User.Identity.Name;
            var currentVet = _vetRepo.GetByUsername(username);
            ViewBag.UserList = _userRepo.Get().Where(r => r.VetId == currentVet.Id).ToList();
            return View(currentVet);
        }

        public string AddCondition(Condition condition)
        {
            return JsonConvert.SerializeObject(_conditionRepo.CreateEntity(condition));
        }

        [HttpGet]
        public ActionResult EditCondition(int id)
        {
            var condition = _conditionRepo.GetEntityByKey(id);
            return View(condition);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult EditCondition(Condition condition)
        {
            _conditionRepo.UpdateEntity(condition.Id, condition);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public void DeleteCondition(int Id)
        {
            _conditionRepo.Delete(Id);
        }

        public string GetUserPets(int userId)
        {
            return JsonConvert.SerializeObject(_userRepo.GetPetsFromUser(userId));
        }

        public string GetPetConditions(int petId)
        {
            var petConditions = _conditionRepo.GetPetConditions(petId);
            return JsonConvert.SerializeObject(petConditions, Formatting.Indented,
                                new JsonSerializerSettings()
                                {
                                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                                });
        }

        public string AddPetCondition(int petId, int conditionId)
        {
            var newPetConditions = _conditionRepo.AddNewPetCondition(petId, conditionId);
            return JsonConvert.SerializeObject(newPetConditions, Formatting.Indented,
                                new JsonSerializerSettings()
                                {
                                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                                });

        }

        public string RemovePetCondition(int petId, int conditionId)
        {
            var updatedPetConditions = _conditionRepo.RemovePetCondition(petId, conditionId);
            return JsonConvert.SerializeObject(updatedPetConditions, Formatting.Indented,
                                new JsonSerializerSettings()
                                {
                                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                                });
        }
    }
}

FnR.VetFront/Views/PostVisitCare/EditCondition.cshtml
@model FnR.Models.Condition

@{
    ViewBag.Title = "EditCondition";
    Layout = "~/Views/Shared/_VetLayout.cshtml";
}

@section styles
{
    <link href="~/Content/MyStyles/postvisitcare.css" rel="stylesheet" />
    @*<link href="~/Content/jHtmlArea/jHtmlArea.css" rel="stylesheet" />*@
}

@section scripts
{
    @*<script src="~/Scripts/jHtmlArea-0.7.5.js"></script>*@
    <script src="~/Scripts/nicEdit/nicEdit.js"></script>
    <script src="~/Scripts/MyScripts/postvisitcare.js"></script>
    <script src="~/Scripts/MyScripts/edit-condition.js"></script>
}

<div class="edit-condition">
    <h2>Condition Management</h2>

    @using (Html.BeginForm("EditCondition", "PostVisitCare", FormMethod.Post, new { id = "edit-condition-form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend><span class="emphasis">@Model.Name</span></legend>

            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.VetId)
            @Html.HiddenFor(model => model.Name)

            @*@Html.TextAreaFor(model => model.Description)*@
            @*<textarea id="Description" name="Description" cols="30" rows="8"></textarea>*@
            @*@Html.HiddenFor(model => model.Description)*@
            @*<textarea id="Description" name="Description" required></textarea>*@
            @Html.TextAreaFor(model => model.Description)
            <div>
                
            </div>

            <div id="createbtn">
                <input type="image" class="btn" alt="submit" src="~/Content/Images/save-button.png" onmouseover="this.src='../Content/Images/save-button-hover.png' " onmouseout="this.src='../Content/Images/save-button.png ' " />
            </div>
        </fieldset>
    }

    <div id="backlistbtn">
        <a href="@Url.Action("Index")" >
            <img src="~/Content/Images/backtolist.png" onmouseover="this.src='../Content/Images/backtolist-button.png' " onmouseout="this.src='../Content/Images/backtolist.png ' " /></a>
    </div>
</div>

FnR.VetFront/Views/PostVisitCare/Index.cshtml
@using FnR.Models
@model FnR.Models.Vet

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_VetLayout.cshtml";
}

@section styles
{
    <link href="~/Content/MyStyles/postvisitcare.css" rel="stylesheet" />
}

@section scripts
{
    <script src="~/Scripts/MyScripts/postvisitcare.js"></script>
}

<input type="hidden" id="post-visit-home-url" value="@Url.Action("Index", "PostVisitCare")"/>
<input type="hidden" id="add-condition-url" value="@Url.Action("AddCondition", "PostVisitCare")"/>
<input type="hidden" id="edit-condition-url" value="@Url.Action("EditCondition", "PostVisitCare")"/>
<input type="hidden" id="delete-condition-url" value="@Url.Action("DeleteCondition", "PostVisitCare")"/>

<input type="hidden" id="getuserpets-url" value="@Url.Action("GetUserPets", "PostVisitCare")"/>
<input type="hidden" id="getpetconditions-url" value="@Url.Action("GetPetConditions", "PostVisitCare")"/>
<input type="hidden" id="addpetcondition-url" value="@Url.Action("AddPetCondition", "PostVisitCare")"/>
<input type="hidden" id="removepetcondition-url" value="@Url.Action("RemovePetCondition", "PostVisitCare")"/>
<input type="hidden" id="vet-id" value="@Model.Id"/>
<div id="far-logo">
    <a href="@Url.Action("Index", "Home")">
        <img src="~/Content/Images/farlogo.png" /></a>
</div>
<div id="main-container">

    <div class="container">
        <img class="logo" src="~/Content/Images/post-logo.png" />
        <h4>Welcome (<span class="emphasis">@Model.Name</span>)</h4>
    </div>
    <div id="condition-management">
        <h3>Condition Management</h3>
        <label>Available Conditions: </label>
        <select id="condition-list">
            <option value="0" selected="selected">-- Select Conditions --</option>
            @foreach (var condition in Model.Conditions)
            {
                <option value="@condition.Id">@condition.Name</option>
            }
        </select>
        <input type="button" id="edit-condition-button" value="Edit Condition >>" />
        <input type="button" id="delete-condition-button" value="- Delete Condition" />
        <input type="button" id="add-condition-button" value="+ Add Condition" />
    </div>

    <div class="selected-pet">
        <h3>Pet Conditions</h3>
        <ul id="added-pet-conditions"></ul>
    </div>

    <div id="condition-assignment">
        <h3>User Condition Assignment</h3>
        <div class="dropdown-list">
            <div class="condition-list-assignment">
                <label>Find Users:</label>
                <select id="user-list" selected="selected">
                    <option value="0">-- Find User --</option>
                    @foreach (var user in (List<User>)ViewBag.UserList)
                    {
                        <option value="@user.Id">@user.FullName</option>
                    }
                </select>
            </div>

            <div class="condition-list-assignment">
                <label>Find Pet:</label>
                <select id="pet-list" selected="selected">
                    <option value="0">-- Find Pet --</option>
                </select>
            </div>

            <div class="condition-list-assignment">
                <label>Find Condition:</label>
                <select id="pet-condition-list">
                    <option value="0" selected="selected">-- Find Conditions --</option>
                    @foreach (var condition in Model.Conditions)
                    {
                        <option value="@condition.Id">@condition.Name</option>
                    }
                </select>
                <input type="button" id="add-pet-condition" value="Add Condition" />
            </div>
        </div>
    </div>
</div>